---
name: "Auto Release"

on:
  push:
    branches:
      - "main"

permissions:
  contents: write
  issues: write
  pull-requests: write
  id-token: write

jobs:
  auto-release:
    name: "Auto Release"
    runs-on: "ubuntu-latest"

    steps:
      - uses: actions/checkout@v3

      - name: Check version
        id: check_version
        run: |
            LAST_VERSION=$(git tag --sort=-v:refname | head -n 1 | xargs)
            CURRENT_VERSION=$(jq -r '.version' free-at-home-metadata.json)
            echo "Last version: $LAST_VERSION"
            echo "Current version: $CURRENT_VERSION"
            BETA_FLAG=$(jq -r '.beta' free-at-home-metadata.json)
            if [ -z "$LAST_VERSION" ] || [ "$(printf '%s\n' "$LAST_VERSION" "$CURRENT_VERSION" | sort -V | head -n1)" != "$LAST_VERSION" ]; then
            echo "New version detected: $CURRENT_VERSION"
            echo "run=true" >> $GITHUB_OUTPUT
            echo "beta=$BETA_FLAG" >> $GITHUB_OUTPUT
            echo "version=$CURRENT_VERSION" >> $GITHUB_OUTPUT
            else
            echo "No new version. Exiting."
            echo "run=false" >> $GITHUB_OUTPUT
            fi

      - name: Use Node.js 18
        if: steps.check_version.outputs.run == 'true'
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "npm"
      - run: npm ci
        if: steps.check_version.outputs.run == 'true'
      - run: npm run buildProd --if-present
        if: steps.check_version.outputs.run == 'true'
      - run: npm run pack --if-present
        if: steps.check_version.outputs.run == 'true'
      - run: bzip2 -z *.tar
        if: steps.check_version.outputs.run == 'true'
      - uses: actions/upload-artifact@v4
        if: steps.check_version.outputs.run == 'true'
        with:
          name: addon
          path: "*.tar.bz2"
      - uses: "softprops/action-gh-release@v2"
        name: "Create Automatic Release"
        if: steps.check_version.outputs.run == 'true'
        with:
          files: "*.tar.bz2"
          tag_name: "v${{ steps.check_version.outputs.version }}"
          draft: false
          prerelease: ${{ steps.check_version.outputs.beta }}
          make_latest: ${{ !steps.check_version.outputs.beta }}
